# Generated by Django 4.2.8 on 2023-12-08 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('querydt', models.DateField(default=datetime.date.today)),
                ('dt', models.IntegerField()),
                ('day', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('night', models.FloatField()),
                ('eve', models.FloatField()),
                ('morn', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
